#!/usr/bin/env php
<?php
$config = json_decode(file_get_contents('acme-config.json'), true);
define('ACME_PATH', $config['acme_path']);
foreach ($config['sites'] as $site) {
    echo "\033[32mStart with '{$site['name']}' Install SSL Certificate Update. \033[0m\n";
    $command = builderCommand($site['domains'], $site['path']);
    shell_exec($command);
    sleep(1);
    $firstDomain = array_shift($site['domains']);
    $domainSSLPath = ACME_PATH . "/{$firstDomain}_ecc/";
    if (is_dir($domainSSLPath)) {
        echo "\033[32mWebsite '{$site['name']}' SSL has been installed to the specified directory \033[0m\n";
        //TODO: copy ssl to site path
        copy("{$domainSSLPath}/{$firstDomain}.cer", $site['cert_file']);
        copy("{$domainSSLPath}/{$firstDomain}.key", $site['key_file']);
        copy("{$domainSSLPath}/ca.cer", $site['ca_file']);
        copy("{$domainSSLPath}/fullchain.cer", $site['fullchain_file']);
    } else {
        echo "\033[31mSSL build failed\033[0m\n";
    }
}
shell_exec($config['reload_command']);
function builderCommand($domains, $path)
{
    $command = ACME_PATH . '/acme.sh --issue ';
    foreach ($domains as $domain) {
        $command .= '-d ' . $domain . ' ';
    }
    $command .= '-w ' . $path . ' --force';
    return $command;
}
